### ISSUE TITLE
Synchronize video listings

### ISSUE THREAD

**Issue by deobald** [pariyatti/kosa2#9]
Getting all the video metadata is easy with the Vimeo API and a public (static) token:

## TODO

* [x] Generate a production Vimeo access token with the [vimeo.com/pariyatti](https://vimeo.com/pariyatti) user
* [x] write scheduled job to sync Vimeo API JSON with db
* [x] API for "latest videos"
    * [x] how do we want to organize videos in the tab? API <> UI symmetry:
    * [x] see [audio wireframe](https://github.com/pariyatti/design/blob/master/mobile-app/renders/resource-05-audios.png), as the video wireframe is mostly empty
    * [x] @brihas - can we get play stats turned on?
    * [x] @brihas - should videos have tags? (currently tags in the API are empty except for https://vimeo.com/315969029 and https://vimeo.com/606918229)
    * [x] @brihas - do we want a manual user interface in Kosa for managing categories? (Vimeo categories are _not_ user-editable, and only available to Vimeo staff: https://developer.vimeo.com/api/reference/categories ; such as "Ads and Commercials", "Animation", etc.)
    * [x] @brihas - do we want to use Vimeo tags for categories instead? (ex. `category:staffpick`)
    * [x] @brihas - do we anticipate other video sources other than vimeo (perhaps for old students)?
* [x] API search

```
curl -H "Authorization: bearer {token}"  https://api.vimeo.com/users/pariyatti/videos
```

* https://help.vimeo.com/hc/en-us/articles/12427789081745-How-do-I-generate-a-personal-access-token
* https://developer.vimeo.com/apps => Pariyatti
    * Generate Access Token
    * Unauthenticated
* A dev access token is stored in the Vault

**Comment by deobald** [comment]
@balwa has deployed this change to staging and production.
